<?xml version="1.0" encoding="utf-8"?><Database Name="医院自助服务机" Class="Hospital_Self_service_MachinesDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=(Local);Initial Catalog=医院自助服务机;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="医院自助服务机ConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.tb_CheckDateInformation" Member="tb_CheckDateInformation">
    <Type Name="tb_CheckDateInformation">
      <Column Name="UserNo" Type="System.String" DbType="Char(10) NOT NULL" CanBeNull="false" />
      <Column Name="CheckTime" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="DoctorCheckName" Type="System.String" DbType="Char(20) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.tb_City" Member="tb_City">
    <Type Name="tb_City">
      <Column Name="No" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="CityName" Type="System.String" DbType="Char(50) NOT NULL" CanBeNull="false" />
      <Column Name="ProvinceNo" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="tb_City_tb_Country" Member="tb_Country" ThisKey="No" OtherKey="CityNo" Type="tb_Country" />
      <Association Name="tb_Province_tb_City" Member="tb_Province" ThisKey="ProvinceNo" OtherKey="No" Type="tb_Province" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tb_Country" Member="tb_Country">
    <Type Name="tb_Country">
      <Column Name="No" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="CountryName" Type="System.String" DbType="Char(50) NOT NULL" CanBeNull="false" />
      <Column Name="CityNo" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="tb_City_tb_Country" Member="tb_City" ThisKey="CityNo" OtherKey="No" Type="tb_City" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tb_Department" Member="tb_Department">
    <Type Name="tb_Department">
      <Column Name="DepartmentNo" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="DepartmentName" Type="System.String" DbType="VarChar(40) NOT NULL" CanBeNull="false" />
      <Association Name="tb_Department_tb_DepartmentDetail" Member="tb_DepartmentDetail" ThisKey="DepartmentNo" OtherKey="DepartmentNo" Type="tb_DepartmentDetail" />
    </Type>
  </Table>
  <Table Name="dbo.tb_DepartmentDetail" Member="tb_DepartmentDetail">
    <Type Name="tb_DepartmentDetail">
      <Column Name="DepartmentDetailNo" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="DepartmentDetailName" Type="System.String" DbType="VarChar(40) NOT NULL" CanBeNull="false" />
      <Column Name="DepartmentNo" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="tb_DepartmentDetail_tb_Symptom" Member="tb_Symptom" ThisKey="DepartmentDetailNo" OtherKey="SuggestDepartmentDetailNo" Type="tb_Symptom" />
      <Association Name="tb_Department_tb_DepartmentDetail" Member="tb_Department" ThisKey="DepartmentNo" OtherKey="DepartmentNo" Type="tb_Department" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tb_DoctorInfo" Member="tb_DoctorInfo">
    <Type Name="tb_DoctorInfo">
      <Column Name="DoctorNo" Type="System.String" DbType="Char(20) NOT NULL" CanBeNull="false" />
      <Column Name="DoctorName" Type="System.String" DbType="Char(20) NOT NULL" CanBeNull="false" />
      <Column Name="DepartmentDetailNo" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="WorkWeekday" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="WorkTime" Type="System.String" DbType="Char(20) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.tb_EthnicGroup" Member="tb_EthnicGroup">
    <Type Name="tb_EthnicGroup">
      <Column Name="EthnicGroupNo" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="EthnicGroupName" Type="System.String" DbType="Char(30) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.tb_DocumentationInformation" Member="tb_DocumentationInformation">
    <Type Name="tb_DocumentationInformation">
      <Column Name="UserNo" Type="System.String" DbType="Char(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="UserName" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="Gender" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Birthday" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="Nation" Type="System.String" DbType="Char(50)" CanBeNull="true" />
      <Column Name="Province" Type="System.String" DbType="Char(30)" CanBeNull="true" />
      <Column Name="City" Type="System.String" DbType="Char(30)" CanBeNull="true" />
      <Column Name="Country" Type="System.String" DbType="Char(50)" CanBeNull="true" />
      <Column Name="EthnicGroup" Type="System.String" DbType="Char(20)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tb_ExpertInfo" Member="tb_ExpertInfo">
    <Type Name="tb_ExpertInfo">
      <Column Name="ExpertInfoNo" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Info" Type="System.String" DbType="VarChar(1000)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tb_ItemInformation" Member="tb_ItemInformation">
    <Type Name="tb_ItemInformation">
      <Column Name="ItemNo" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ItemName" Type="System.String" DbType="Char(100) NOT NULL" CanBeNull="false" />
      <Column Name="ReferenceValue" Type="System.String" DbType="Char(30) NOT NULL" CanBeNull="false" />
      <Column Name="Unit" Type="System.String" DbType="Char(20) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.tb_LimitCount" Member="tb_LimitCount">
    <Type Name="tb_LimitCount">
      <Column Name="SpecificTimePeriod" Type="System.String" DbType="Char(20)" CanBeNull="true" />
      <Column Name="LimitCount" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tb_Nation" Member="tb_Nation">
    <Type Name="tb_Nation">
      <Column Name="No" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="NationName" Type="System.String" DbType="Char(50) NOT NULL" CanBeNull="false" />
      <Association Name="tb_Nation_tb_Province" Member="tb_Province" ThisKey="No" OtherKey="NationNo" Type="tb_Province" />
    </Type>
  </Table>
  <Table Name="dbo.tb_PatientCheckInformation" Member="tb_PatientCheckInformation">
    <Type Name="tb_PatientCheckInformation">
      <Column Name="UserNo" Type="System.String" DbType="Char(10) NOT NULL" CanBeNull="false" />
      <Column Name="ItemNo" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ResultScore" Type="System.String" DbType="Char(10) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.tb_Payment" Member="tb_Payment">
    <Type Name="tb_Payment">
      <Column Name="UserNo" Type="System.String" DbType="Char(10) NOT NULL" CanBeNull="false" />
      <Column Name="PayItemNo" Type="System.String" DbType="Char(20) NOT NULL" CanBeNull="false" />
      <Column Name="PayTime" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="Flat" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tb_Price" Member="tb_Price">
    <Type Name="tb_Price">
      <Column Name="PayItemNo" Type="System.String" DbType="Char(20) NOT NULL" CanBeNull="false" />
      <Column Name="PayItemName" Type="System.String" DbType="Char(100) NOT NULL" CanBeNull="false" />
      <Column Name="Price" Type="System.Decimal" DbType="Decimal(5,2) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.tb_Province" Member="tb_Province">
    <Type Name="tb_Province">
      <Column Name="No" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ProvinceName" Type="System.String" DbType="Char(50) NOT NULL" CanBeNull="false" />
      <Column Name="NationNo" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="tb_Province_tb_City" Member="tb_City" ThisKey="No" OtherKey="ProvinceNo" Type="tb_City" />
      <Association Name="tb_Nation_tb_Province" Member="tb_Nation" ThisKey="NationNo" OtherKey="No" Type="tb_Nation" IsForeignKey="true" DeleteRule="CASCADE" />
    </Type>
  </Table>
  <Table Name="dbo.tb_Registerd" Member="tb_Registerd">
    <Type Name="tb_Registerd">
      <Column Name="UserNo" Type="System.String" DbType="Char(10) NOT NULL" CanBeNull="false" />
      <Column Name="DepartmentDetailNo" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="RegisterTime" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="SpecificTimePeriod" Type="System.String" DbType="Char(20) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.tb_RegisterdCancelCount" Member="tb_RegisterdCancelCount">
    <Type Name="tb_RegisterdCancelCount">
      <Column Name="UserNo" Type="System.String" DbType="Char(10)" CanBeNull="true" />
      <Column Name="Count" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tb_RegisterdTime" Member="tb_RegisterdTime">
    <Type Name="tb_RegisterdTime">
      <Column Name="No" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="RegisterTime" Type="System.String" DbType="Char(20) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.tb_Symptom" Member="tb_Symptom">
    <Type Name="tb_Symptom">
      <Column Name="SymptomNo" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Symptom" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="SuggestDepartmentDetailNo" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="tb_DepartmentDetail_tb_Symptom" Member="tb_DepartmentDetail" ThisKey="SuggestDepartmentDetailNo" OtherKey="DepartmentDetailNo" Type="tb_DepartmentDetail" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
      <Association Name="tb_SymptomStype_tb_Symptom" Member="tb_SymptomStype" ThisKey="SymptomNo" OtherKey="SymptomStypeNo" Type="tb_SymptomStype" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tb_SymptomStype" Member="tb_SymptomStype">
    <Type Name="tb_SymptomStype">
      <Column Name="SymptomStypeNo" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Symptom" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Association Name="tb_SymptomStype_tb_Symptom" Member="tb_Symptom" ThisKey="SymptomStypeNo" OtherKey="SymptomNo" Type="tb_Symptom" />
    </Type>
  </Table>
  <Table Name="dbo.tb_User" Member="tb_User">
    <Type Name="tb_User">
      <Column Name="UserNo" Type="System.String" DbType="Char(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="UserName" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="Password" Type="System.Data.Linq.Binary" DbType="VarBinary(20) NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="IsActivated" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="LoginFailCount" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>